### ISSUE TITLE
Shooter pass or don't pass bet

### ISSUE THREAD

**Issue by mikecoop** [mikecoop/casino-craps#11]
The shooter is required to make a pass or don't pass line bet before shooting for a round.

**Comment by rlinsky** [comment]
This is still ongoing..

**Comment by mikecoop** [comment]
I amended the requirement slightly to make it so the shooter had to have an active bet to be able to roll. I thought it would be a little easier than having them keep making pass or don't pass bets. If we want to have it the old way I can change it pretty easily.

**Comment by rlinsky** [comment]
Ok no problem.  We might as well leave it as is then, it will be easier to change my documentation than modify the game and send out a new version.

Thanks
