### ISSUE TITLE
Betting Odds

### ISSUE THREAD

**Issue by rlinsky** [mikecoop/casino-craps#18]
I'm not sure if you're too worried about this, but several of the odds that are coded into the game are different than the ones on the GUI.  I'm not sure who will notice to be honest...

**Comment by mikecoop** [comment]
Hmm never noticed that, good catch. It's not hard to change the odds but like you said it's probably not that big of a deal as long as we document what they are. It's funny I got the image from the wiki article where the odds were listed.
